Separate login view
HaiSSer666/NewsAggregator pull request #2
Opened 2018-04-15 18:34 UTC by HaiSSer666

created a new login form

2018-04-15 18:58 UTC, MaxRandom requested changes

2018-04-15 18:58 UTC, MaxRandom commented on NewsAggregator/Classes/LoginManager.cs
> +                MessageBox.Show("Error is occured. Authentication was not successful.\n Try to start app one more time.");
UI code should not be a part of Login Manager

2018-04-15 18:58 UTC, MaxRandom commented on NewsAggregator/Classes/Serealizator.cs
> +// c:\users\admin\documents\visual studio 2015\Projects\NewsAggregator\
Remove this comment

2018-04-15 18:58 UTC, MaxRandom commented on NewsAggregator/Program.cs
> +            loginManager.InitialiseSession();
`InitialiseSession` -> `InitializeSession`

2018-04-16 16:38 UTC, HaiSSer666 commented
change code according to @MaxRandom comments

2018-04-18 18:27 UTC, MaxRandom approved these changes

2018-04-19 06:25 UTC, merged